import type { Metadata } from 'next';
import { Space_Grotesk } from 'next/font/google';
import BackgroundAnimation from '@/app/ui/background-animation';
import './globals.css';

const spaceGrotesk = Space_Grotesk({
	variable: '--font-space-grotesk',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Horror Loop App',
	description: 'Generated by create next app',
};

type LayoutProps = { children: React.ReactNode };

export default function RootLayout({ children }: Readonly<LayoutProps>) {
	return (
		<html lang='en' dir='ltr'>
			<body className={`${spaceGrotesk.variable} font-spaceGrotesk antialiased`}>
				<main className='relative z-20'>{children}</main>
				<BackgroundAnimation />
			</body>
		</html>
	);
}
